AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RoleName:
    Type: String
    Default: org-osm-api
    Description: Role name for all accounts
  OsmLambdaMainAccountId:
    Type: String
    Default: ''
    Description: Main account id where OSM lambda is located

Resources:
  OsmTrustRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Path: /
      Policies:
        - PolicyName: default
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: 'arn:aws:s3:::*'
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:GetRole
                  - iam:ListAttachedRolePolicies
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListRolePolicies
                  - iam:GetRolePolic
                Resource: 'arn:aws:iam:::*'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${MainAccountId}:root'
                - { MainAccountId: !Ref OsmLambdaMainAccountId }
            Action: sts:AssumeRole
      Tags:
        - Key: 'application'
          Value: 'osm'
