AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RoleName:
    Type: String
    Default: org-osm-api
    Description: Role name for all accounts
  OsmLambdaMainAccountId:
    Type: String
    Default: ''
    Description: Main account id where osm lambdas are located

Resources:
  OsmTrustRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Path: /
      Policies:
        - PolicyName: default
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: 'arn:aws:s3:::*'
              - Effect: Allow
                Action:
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:ListAttachedRolePolicies
                  - iam:ListPolicies
                  - iam:ListRolePolicies
                Resource: 'arn:aws:iam:::*'
              - Effect: Allow
                Action:
                  - iam:ListRoles
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:Describe*
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource:
                  - arn:aws:ssm:*:*:document/*
                  - arn:aws:ec2:*:*:instance/*
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${OsmLambdaMainAccountId}:root
            Action: sts:AssumeRole
      Tags:
        - Key: 'application'
          Value: 'osm'
